### ISSUE TITLE
[ENHANCEMENT] TSDoc support

### ISSUE THREAD

**Issue by kravetsone** [twoslashes/twoslash#20]
For example, VSCode works fine with [TSDoc](https://tsdoc.org/) comments ([@link](https://tsdoc.org/pages/tags/link/))

![image](https://github.com/twoslashes/twoslash/assets/57632712/c7c3efd6-0ead-45ec-81a9-c12dc9d70958)
![image](https://github.com/twoslashes/twoslash/assets/57632712/03650bfe-98ce-4e35-aad4-102ece1227b8)

But [twoslash](https://github.com/twoslashes/twoslash) not

![image](https://github.com/twoslashes/twoslash/assets/57632712/6f69d6a4-41d7-46c1-928b-e468bbf31f23)

Example of [@link](https://tsdoc.org/pages/tags/link/) - https://github.com/gramiojs/types/blob/262e05d47733613f9c4d2c0e290f3c347ef08881/out/methods.d.ts#L18
Deployed documentation - https://gramio.netlify.app/types/#usage-with-gramio-keyboards

**Comment by antfu** [comment]
Oh I didn't know this syntax is vaild - we probably need a little parser. And btw Twoslash does not handle how you render them - the is the VitePress plugin's behavior: https://github.com/shikijs/shiki/blob/1455220494768952d291736992f316d50644748e/packages/vitepress-twoslash/src/renderer-floating-vue.ts#L154

You may want to open an issue or PR there instead. Thanks.
