### ISSUE TITLE
[2304] Cannot find name 'ReadonlyArray'

### ISSUE THREAD

**Issue by charpeni** [twoslashes/twoslash#45]
I'm using `twoslash-cdn` and it doesn't recognize `ReadonlyArray`, even when using `typescript@5.5.2`.

```ts
import { createTwoslashFromCDN } from "twoslash-cdn";

const twoslash = createTwoslashFromCDN();
const twoslashResult = await twoslash.run(
  `
  type Test = ReadonlyArray<string>;
`,
  "ts",
  {
    compilerOptions: {
      lib: ["esnext", "dom"],
    },
  }
);

console.log(twoslashResult);
```

```
Typescript version used by `createTwoslashFromCDN`: 5.5.2
`fsMap` sources:
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.decorators.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.decorators.legacy.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.dom.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.dom.iterable.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.webworker.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.webworker.importscripts.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.webworker.iterable.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.scripthost.d.ts
https://playgroundcdn.typescriptlang.org/cdn/5.5.2/typescript/lib/lib.es5.d.ts

----------------

Uncaught Error: 
## Errors were thrown in the sample, but not included in an error tag

These errors were not marked as being expected: 2304. 
Expected: // @errors: 2304

Compiler Errors:

index.ts
  [2304] 15 - Cannot find name 'ReadonlyArray'.
    at validateCodeForErrors (twoslash-cdn.js?v=9e7f0781:208593:20)
    at twoslasher2 (twoslash-cdn.js?v=9e7f0781:208913:7)
    at runSync (twoslash-cdn.js?v=9e7f0781:209461:12)
    at Object.run (twoslash-cdn.js?v=9e7f0781:209458:12)
    at async App.tsx:9:24
```

I can definitely see the interface for `ReadonlyArray` defined within `lib.es5.d.ts`.

[🔗 CodeSandbox](https://codesandbox.io/p/devbox/stoic-river-qq7mr9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxywmwuz00073b6k3kho92v6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxywmwuz00023b6k0vw7p0we%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxywmwuz00043b6kvz4424jv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxywmwuz00063b6k68sd1cil%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxywmwuz00023b6k0vw7p0we%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxywmwuz00013b6ktyggx8v2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxywmwuz00023b6k0vw7p0we%2522%252C%2522activeTabId%2522%253A%2522clxywmwuz00013b6ktyggx8v2%2522%257D%252C%2522clxywmwuz00063b6k68sd1cil%2522%253A%257B%2522id%2522%253A%2522clxywmwuz00063b6k68sd1cil%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxywmwuz00053b6ku79ukllc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxywmwuz00053b6ku79ukllc%2522%257D%252C%2522clxywmwuz00043b6kvz4424jv%2522%253A%257B%2522id%2522%253A%2522clxywmwuz00043b6kvz4424jv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxywmwuz00033b6k3dvxbw3f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxywmwuz00033b6k3dvxbw3f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) with a reproduction.

**Comment by antfu** [comment]
Ah, you will need to put `compilerOptions` in createTwoslash:

```ts
const twoslash = createTwoslashFromCDN({
  compilerOptions: {
    lib: ["esnext", "dom"],
  },
});
```
